version: '3.8'

services:
  tree-of-life-db:
    image: mysql:8.0.32
    container_name: tree-of-life-db
    hostname: tree-of-life-db
    environment:
      - MYSQL_ROOT_PASSWORD=GFA2mc3QSe
      - MYSQL_USER=tree-of-life-app
      - MYSQL_PASSWORD=A0h3dIzdy8
      - MYSQL_DATABASE=tree_of_life
    volumes:
      - $PWD/docker/config/mysql.conf.d:/etc/mysql/conf.d/:ro
      - tree_of_life_db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  tree_of_life_db_data:
